<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNQ86ddi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNQ86ddi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNQ86ddi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNQ86ddi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNQ86ddi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NQ86ddi',
    'container.build_id' => '5b0ddd6e',
    'container.build_time' => 1597238873,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNQ86ddi');
