<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY1j06Ns\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY1j06Ns/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY1j06Ns.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY1j06Ns\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerY1j06Ns\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Y1j06Ns',
    'container.build_id' => 'e4656d3a',
    'container.build_time' => 1597232420,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY1j06Ns');
