<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'company' => [[], ['_controller' => 'App\\Controller\\CompanyController::index'], [], [['text', '/company']], [], []],
    'companyCreate' => [[], ['_controller' => 'App\\Controller\\CompanyController::createCustomer'], [], [['text', '/']], [], []],
    'show' => [[], ['_controller' => 'App\\Controller\\CustomerController::show'], [], [['text', '/show']], [], []],
    'add_customer' => [[], ['_controller' => 'App\\Controller\\CustomerController::addCustomer'], [], [['text', '/add']], [], []],
    'all_customer' => [[], ['_controller' => 'App\\Controller\\CustomerController::index'], [], [['text', '/customer']], [], []],
    'customer_by_id' => [['id'], ['_controller' => 'App\\Controller\\CustomerController::getById'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/customer']], [], []],
    'delete_ustomer_by_id' => [['id'], ['_controller' => 'App\\Controller\\CustomerController::destroy'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/customer/delete']], [], []],
    'add_order' => [[], ['_controller' => 'App\\Controller\\OrderController::addCustomer'], [], [['text', '/addOrder']], [], []],
    'all_orders' => [[], ['_controller' => 'App\\Controller\\OrderController::index'], [], [['text', '/order']], [], []],
    'order_by_id' => [['id'], ['_controller' => 'App\\Controller\\OrderController::getById'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/order']], [], []],
    'order_ustomer_by_id' => [['id'], ['_controller' => 'App\\Controller\\OrderController::destroy'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/order/delete']], [], []],
];
